export {default as Team} from './Team'
export {default as Mission} from './Mission'
export {default as Goals} from './Goals'
export {default as JoinUs} from './JoinUs'
export {default as OurStory} from './OurStory'
// export {default as SwiperTest} from './SwiperTest.jsx'