export {default as Home} from './Home'
export {default as About} from './About'
export {default as SignUp} from './SignUp'
export {default as FindATutor} from './FindATutor'
export {default as JoinAsTutor} from './JoinAsTutor'
export {default as Courses} from './Courses'
export {default as SignIn} from './SignIn'